"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountAddressRestrictionTransactionBodyDTOToJSON = exports.AccountAddressRestrictionTransactionBodyDTOFromJSONTyped = exports.AccountAddressRestrictionTransactionBodyDTOFromJSON = exports.instanceOfAccountAddressRestrictionTransactionBodyDTO = void 0;
const runtime_1 = require("../runtime");
const AccountRestrictionFlagsEnum_1 = require("./AccountRestrictionFlagsEnum");
/**
 * Check if a given object implements the AccountAddressRestrictionTransactionBodyDTO interface.
 */
function instanceOfAccountAddressRestrictionTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "restrictionFlags" in value;
    return isInstance;
}
exports.instanceOfAccountAddressRestrictionTransactionBodyDTO = instanceOfAccountAddressRestrictionTransactionBodyDTO;
function AccountAddressRestrictionTransactionBodyDTOFromJSON(json) {
    return AccountAddressRestrictionTransactionBodyDTOFromJSONTyped(json, false);
}
exports.AccountAddressRestrictionTransactionBodyDTOFromJSON = AccountAddressRestrictionTransactionBodyDTOFromJSON;
function AccountAddressRestrictionTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumFromJSON)(json['restrictionFlags']),
        'restrictionAdditions': !(0, runtime_1.exists)(json, 'restrictionAdditions') ? undefined : json['restrictionAdditions'],
        'restrictionDeletions': !(0, runtime_1.exists)(json, 'restrictionDeletions') ? undefined : json['restrictionDeletions'],
    };
}
exports.AccountAddressRestrictionTransactionBodyDTOFromJSONTyped = AccountAddressRestrictionTransactionBodyDTOFromJSONTyped;
function AccountAddressRestrictionTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumToJSON)(value.restrictionFlags),
        'restrictionAdditions': value.restrictionAdditions,
        'restrictionDeletions': value.restrictionDeletions,
    };
}
exports.AccountAddressRestrictionTransactionBodyDTOToJSON = AccountAddressRestrictionTransactionBodyDTOToJSON;
