"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountKeyLinkTransactionBodyDTOToJSON = exports.AccountKeyLinkTransactionBodyDTOFromJSONTyped = exports.AccountKeyLinkTransactionBodyDTOFromJSON = exports.instanceOfAccountKeyLinkTransactionBodyDTO = void 0;
const LinkActionEnum_1 = require("./LinkActionEnum");
/**
 * Check if a given object implements the AccountKeyLinkTransactionBodyDTO interface.
 */
function instanceOfAccountKeyLinkTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "linkedPublicKey" in value;
    isInstance = isInstance && "linkAction" in value;
    return isInstance;
}
exports.instanceOfAccountKeyLinkTransactionBodyDTO = instanceOfAccountKeyLinkTransactionBodyDTO;
function AccountKeyLinkTransactionBodyDTOFromJSON(json) {
    return AccountKeyLinkTransactionBodyDTOFromJSONTyped(json, false);
}
exports.AccountKeyLinkTransactionBodyDTOFromJSON = AccountKeyLinkTransactionBodyDTOFromJSON;
function AccountKeyLinkTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'linkedPublicKey': json['linkedPublicKey'],
        'linkAction': (0, LinkActionEnum_1.LinkActionEnumFromJSON)(json['linkAction']),
    };
}
exports.AccountKeyLinkTransactionBodyDTOFromJSONTyped = AccountKeyLinkTransactionBodyDTOFromJSONTyped;
function AccountKeyLinkTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'linkedPublicKey': value.linkedPublicKey,
        'linkAction': (0, LinkActionEnum_1.LinkActionEnumToJSON)(value.linkAction),
    };
}
exports.AccountKeyLinkTransactionBodyDTOToJSON = AccountKeyLinkTransactionBodyDTOToJSON;
