"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountNamesDTOToJSON = exports.AccountNamesDTOFromJSONTyped = exports.AccountNamesDTOFromJSON = exports.instanceOfAccountNamesDTO = void 0;
/**
 * Check if a given object implements the AccountNamesDTO interface.
 */
function instanceOfAccountNamesDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "names" in value;
    return isInstance;
}
exports.instanceOfAccountNamesDTO = instanceOfAccountNamesDTO;
function AccountNamesDTOFromJSON(json) {
    return AccountNamesDTOFromJSONTyped(json, false);
}
exports.AccountNamesDTOFromJSON = AccountNamesDTOFromJSON;
function AccountNamesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'address': json['address'],
        'names': json['names'],
    };
}
exports.AccountNamesDTOFromJSONTyped = AccountNamesDTOFromJSONTyped;
function AccountNamesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'address': value.address,
        'names': value.names,
    };
}
exports.AccountNamesDTOToJSON = AccountNamesDTOToJSON;
