"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountOrderByEnumToJSON = exports.AccountOrderByEnumFromJSONTyped = exports.AccountOrderByEnumFromJSON = exports.AccountOrderByEnum = void 0;
/**
 *
 * @export
 */
exports.AccountOrderByEnum = {
    Id: 'id',
    Balance: 'balance'
};
function AccountOrderByEnumFromJSON(json) {
    return AccountOrderByEnumFromJSONTyped(json, false);
}
exports.AccountOrderByEnumFromJSON = AccountOrderByEnumFromJSON;
function AccountOrderByEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.AccountOrderByEnumFromJSONTyped = AccountOrderByEnumFromJSONTyped;
function AccountOrderByEnumToJSON(value) {
    return value;
}
exports.AccountOrderByEnumToJSON = AccountOrderByEnumToJSON;
