"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountLinkPublicKeyDTOToJSON = exports.AccountLinkPublicKeyDTOFromJSONTyped = exports.AccountLinkPublicKeyDTOFromJSON = exports.instanceOfAccountLinkPublicKeyDTO = void 0;
/**
 * Check if a given object implements the AccountLinkPublicKeyDTO interface.
 */
function instanceOfAccountLinkPublicKeyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "publicKey" in value;
    return isInstance;
}
exports.instanceOfAccountLinkPublicKeyDTO = instanceOfAccountLinkPublicKeyDTO;
function AccountLinkPublicKeyDTOFromJSON(json) {
    return AccountLinkPublicKeyDTOFromJSONTyped(json, false);
}
exports.AccountLinkPublicKeyDTOFromJSON = AccountLinkPublicKeyDTOFromJSON;
function AccountLinkPublicKeyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'publicKey': json['publicKey'],
    };
}
exports.AccountLinkPublicKeyDTOFromJSONTyped = AccountLinkPublicKeyDTOFromJSONTyped;
function AccountLinkPublicKeyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'publicKey': value.publicKey,
    };
}
exports.AccountLinkPublicKeyDTOToJSON = AccountLinkPublicKeyDTOToJSON;
