"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountMosaicRestrictionTransactionDTOToJSON = exports.AccountMosaicRestrictionTransactionDTOFromJSONTyped = exports.AccountMosaicRestrictionTransactionDTOFromJSON = exports.instanceOfAccountMosaicRestrictionTransactionDTO = void 0;
const runtime_1 = require("../runtime");
const AccountRestrictionFlagsEnum_1 = require("./AccountRestrictionFlagsEnum");
const NetworkTypeEnum_1 = require("./NetworkTypeEnum");
/**
 * Check if a given object implements the AccountMosaicRestrictionTransactionDTO interface.
 */
function instanceOfAccountMosaicRestrictionTransactionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "signature" in value;
    isInstance = isInstance && "signerPublicKey" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "network" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "maxFee" in value;
    isInstance = isInstance && "deadline" in value;
    isInstance = isInstance && "restrictionFlags" in value;
    return isInstance;
}
exports.instanceOfAccountMosaicRestrictionTransactionDTO = instanceOfAccountMosaicRestrictionTransactionDTO;
function AccountMosaicRestrictionTransactionDTOFromJSON(json) {
    return AccountMosaicRestrictionTransactionDTOFromJSONTyped(json, false);
}
exports.AccountMosaicRestrictionTransactionDTOFromJSON = AccountMosaicRestrictionTransactionDTOFromJSON;
function AccountMosaicRestrictionTransactionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'size': json['size'],
        'signature': json['signature'],
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumFromJSON)(json['network']),
        'type': json['type'],
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumFromJSON)(json['restrictionFlags']),
        'restrictionAdditions': !(0, runtime_1.exists)(json, 'restrictionAdditions') ? undefined : json['restrictionAdditions'],
        'restrictionDeletions': !(0, runtime_1.exists)(json, 'restrictionDeletions') ? undefined : json['restrictionDeletions'],
    };
}
exports.AccountMosaicRestrictionTransactionDTOFromJSONTyped = AccountMosaicRestrictionTransactionDTOFromJSONTyped;
function AccountMosaicRestrictionTransactionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'size': value.size,
        'signature': value.signature,
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumToJSON)(value.network),
        'type': value.type,
        'maxFee': value.maxFee,
        'deadline': value.deadline,
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumToJSON)(value.restrictionFlags),
        'restrictionAdditions': value.restrictionAdditions,
        'restrictionDeletions': value.restrictionDeletions,
    };
}
exports.AccountMosaicRestrictionTransactionDTOToJSON = AccountMosaicRestrictionTransactionDTOToJSON;
