"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountLinkVotingKeysDTOToJSON = exports.AccountLinkVotingKeysDTOFromJSONTyped = exports.AccountLinkVotingKeysDTOFromJSON = exports.instanceOfAccountLinkVotingKeysDTO = void 0;
const AccountLinkVotingKeyDTO_1 = require("./AccountLinkVotingKeyDTO");
/**
 * Check if a given object implements the AccountLinkVotingKeysDTO interface.
 */
function instanceOfAccountLinkVotingKeysDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "publicKeys" in value;
    return isInstance;
}
exports.instanceOfAccountLinkVotingKeysDTO = instanceOfAccountLinkVotingKeysDTO;
function AccountLinkVotingKeysDTOFromJSON(json) {
    return AccountLinkVotingKeysDTOFromJSONTyped(json, false);
}
exports.AccountLinkVotingKeysDTOFromJSON = AccountLinkVotingKeysDTOFromJSON;
function AccountLinkVotingKeysDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'publicKeys': (json['publicKeys'].map(AccountLinkVotingKeyDTO_1.AccountLinkVotingKeyDTOFromJSON)),
    };
}
exports.AccountLinkVotingKeysDTOFromJSONTyped = AccountLinkVotingKeysDTOFromJSONTyped;
function AccountLinkVotingKeysDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'publicKeys': (value.publicKeys.map(AccountLinkVotingKeyDTO_1.AccountLinkVotingKeyDTOToJSON)),
    };
}
exports.AccountLinkVotingKeysDTOToJSON = AccountLinkVotingKeysDTOToJSON;
