"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountOperationRestrictionTransactionBodyDTOToJSON = exports.AccountOperationRestrictionTransactionBodyDTOFromJSONTyped = exports.AccountOperationRestrictionTransactionBodyDTOFromJSON = exports.instanceOfAccountOperationRestrictionTransactionBodyDTO = void 0;
const AccountRestrictionFlagsEnum_1 = require("./AccountRestrictionFlagsEnum");
const TransactionTypeEnum_1 = require("./TransactionTypeEnum");
/**
 * Check if a given object implements the AccountOperationRestrictionTransactionBodyDTO interface.
 */
function instanceOfAccountOperationRestrictionTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "restrictionFlags" in value;
    isInstance = isInstance && "restrictionAdditions" in value;
    isInstance = isInstance && "restrictionDeletions" in value;
    return isInstance;
}
exports.instanceOfAccountOperationRestrictionTransactionBodyDTO = instanceOfAccountOperationRestrictionTransactionBodyDTO;
function AccountOperationRestrictionTransactionBodyDTOFromJSON(json) {
    return AccountOperationRestrictionTransactionBodyDTOFromJSONTyped(json, false);
}
exports.AccountOperationRestrictionTransactionBodyDTOFromJSON = AccountOperationRestrictionTransactionBodyDTOFromJSON;
function AccountOperationRestrictionTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        restrictionFlags: (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumFromJSON)(json["restrictionFlags"]),
        restrictionAdditions: json["restrictionAdditions"].map(TransactionTypeEnum_1.TransactionTypeEnumFromJSON),
        restrictionDeletions: json["restrictionDeletions"].map(TransactionTypeEnum_1.TransactionTypeEnumFromJSON),
    };
}
exports.AccountOperationRestrictionTransactionBodyDTOFromJSONTyped = AccountOperationRestrictionTransactionBodyDTOFromJSONTyped;
function AccountOperationRestrictionTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        restrictionFlags: (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumToJSON)(value.restrictionFlags),
        restrictionAdditions: value.restrictionAdditions.map(TransactionTypeEnum_1.TransactionTypeEnumToJSON),
        restrictionDeletions: value.restrictionDeletions.map(TransactionTypeEnum_1.TransactionTypeEnumToJSON),
    };
}
exports.AccountOperationRestrictionTransactionBodyDTOToJSON = AccountOperationRestrictionTransactionBodyDTOToJSON;
