"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddressesToJSON = exports.AddressesFromJSONTyped = exports.AddressesFromJSON = exports.instanceOfAddresses = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Addresses interface.
 */
function instanceOfAddresses(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfAddresses = instanceOfAddresses;
function AddressesFromJSON(json) {
    return AddressesFromJSONTyped(json, false);
}
exports.AddressesFromJSON = AddressesFromJSON;
function AddressesFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        addresses: !(0, runtime_1.exists)(json, "addresses") ? undefined : json["addresses"],
    };
}
exports.AddressesFromJSONTyped = AddressesFromJSONTyped;
function AddressesToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        addresses: value.addresses,
    };
}
exports.AddressesToJSON = AddressesToJSON;
