"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AggregateTransactionBodyExtendedDTOToJSON = exports.AggregateTransactionBodyExtendedDTOFromJSONTyped = exports.AggregateTransactionBodyExtendedDTOFromJSON = exports.instanceOfAggregateTransactionBodyExtendedDTO = void 0;
const runtime_1 = require("../runtime");
const CosignatureDTO_1 = require("./CosignatureDTO");
const EmbeddedTransactionInfoDTO_1 = require("./EmbeddedTransactionInfoDTO");
/**
 * Check if a given object implements the AggregateTransactionBodyExtendedDTO interface.
 */
function instanceOfAggregateTransactionBodyExtendedDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "transactionsHash" in value;
    return isInstance;
}
exports.instanceOfAggregateTransactionBodyExtendedDTO = instanceOfAggregateTransactionBodyExtendedDTO;
function AggregateTransactionBodyExtendedDTOFromJSON(json) {
    return AggregateTransactionBodyExtendedDTOFromJSONTyped(json, false);
}
exports.AggregateTransactionBodyExtendedDTOFromJSON = AggregateTransactionBodyExtendedDTOFromJSON;
function AggregateTransactionBodyExtendedDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'transactionsHash': json['transactionsHash'],
        'cosignatures': !(0, runtime_1.exists)(json, 'cosignatures') ? undefined : (json['cosignatures'].map(CosignatureDTO_1.CosignatureDTOFromJSON)),
        'transactions': !(0, runtime_1.exists)(json, 'transactions') ? undefined : (json['transactions'].map(EmbeddedTransactionInfoDTO_1.EmbeddedTransactionInfoDTOFromJSON)),
    };
}
exports.AggregateTransactionBodyExtendedDTOFromJSONTyped = AggregateTransactionBodyExtendedDTOFromJSONTyped;
function AggregateTransactionBodyExtendedDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'transactionsHash': value.transactionsHash,
        'cosignatures': value.cosignatures === undefined ? undefined : (value.cosignatures.map(CosignatureDTO_1.CosignatureDTOToJSON)),
        'transactions': value.transactions === undefined ? undefined : (value.transactions.map(EmbeddedTransactionInfoDTO_1.EmbeddedTransactionInfoDTOToJSON)),
    };
}
exports.AggregateTransactionBodyExtendedDTOToJSON = AggregateTransactionBodyExtendedDTOToJSON;
