"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AliasDTOToJSON = exports.AliasDTOFromJSONTyped = exports.AliasDTOFromJSON = exports.instanceOfAliasDTO = void 0;
const runtime_1 = require("../runtime");
const AliasTypeEnum_1 = require("./AliasTypeEnum");
/**
 * Check if a given object implements the AliasDTO interface.
 */
function instanceOfAliasDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    return isInstance;
}
exports.instanceOfAliasDTO = instanceOfAliasDTO;
function AliasDTOFromJSON(json) {
    return AliasDTOFromJSONTyped(json, false);
}
exports.AliasDTOFromJSON = AliasDTOFromJSON;
function AliasDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'type': (0, AliasTypeEnum_1.AliasTypeEnumFromJSON)(json['type']),
        'mosaicId': !(0, runtime_1.exists)(json, 'mosaicId') ? undefined : json['mosaicId'],
        'address': !(0, runtime_1.exists)(json, 'address') ? undefined : json['address'],
    };
}
exports.AliasDTOFromJSONTyped = AliasDTOFromJSONTyped;
function AliasDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'type': (0, AliasTypeEnum_1.AliasTypeEnumToJSON)(value.type),
        'mosaicId': value.mosaicId,
        'address': value.address,
    };
}
exports.AliasDTOToJSON = AliasDTOToJSON;
