"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BlockInfoDTOToJSON = exports.BlockInfoDTOFromJSONTyped = exports.BlockInfoDTOFromJSON = exports.instanceOfBlockInfoDTO = void 0;
const BlockInfoDTOBlock_1 = require("./BlockInfoDTOBlock");
const BlockMetaDTO_1 = require("./BlockMetaDTO");
/**
 * Check if a given object implements the BlockInfoDTO interface.
 */
function instanceOfBlockInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "block" in value;
    return isInstance;
}
exports.instanceOfBlockInfoDTO = instanceOfBlockInfoDTO;
function BlockInfoDTOFromJSON(json) {
    return BlockInfoDTOFromJSONTyped(json, false);
}
exports.BlockInfoDTOFromJSON = BlockInfoDTOFromJSON;
function BlockInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json["id"],
        meta: (0, BlockMetaDTO_1.BlockMetaDTOFromJSON)(json["meta"]),
        block: (0, BlockInfoDTOBlock_1.BlockInfoDTOBlockFromJSON)(json["block"]),
    };
}
exports.BlockInfoDTOFromJSONTyped = BlockInfoDTOFromJSONTyped;
function BlockInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        meta: (0, BlockMetaDTO_1.BlockMetaDTOToJSON)(value.meta),
        block: (0, BlockInfoDTOBlock_1.BlockInfoDTOBlockToJSON)(value.block),
    };
}
exports.BlockInfoDTOToJSON = BlockInfoDTOToJSON;
