"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChainInfoDTOToJSON = exports.ChainInfoDTOFromJSONTyped = exports.ChainInfoDTOFromJSON = exports.instanceOfChainInfoDTO = void 0;
const FinalizedBlockDTO_1 = require("./FinalizedBlockDTO");
/**
 * Check if a given object implements the ChainInfoDTO interface.
 */
function instanceOfChainInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "scoreHigh" in value;
    isInstance = isInstance && "scoreLow" in value;
    isInstance = isInstance && "latestFinalizedBlock" in value;
    return isInstance;
}
exports.instanceOfChainInfoDTO = instanceOfChainInfoDTO;
function ChainInfoDTOFromJSON(json) {
    return ChainInfoDTOFromJSONTyped(json, false);
}
exports.ChainInfoDTOFromJSON = ChainInfoDTOFromJSON;
function ChainInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        height: json["height"],
        scoreHigh: json["scoreHigh"],
        scoreLow: json["scoreLow"],
        latestFinalizedBlock: (0, FinalizedBlockDTO_1.FinalizedBlockDTOFromJSON)(json["latestFinalizedBlock"]),
    };
}
exports.ChainInfoDTOFromJSONTyped = ChainInfoDTOFromJSONTyped;
function ChainInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        height: value.height,
        scoreHigh: value.scoreHigh,
        scoreLow: value.scoreLow,
        latestFinalizedBlock: (0, FinalizedBlockDTO_1.FinalizedBlockDTOToJSON)(value.latestFinalizedBlock),
    };
}
exports.ChainInfoDTOToJSON = ChainInfoDTOToJSON;
