"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommunicationTimestampsDTOToJSON = exports.CommunicationTimestampsDTOFromJSONTyped = exports.CommunicationTimestampsDTOFromJSON = exports.instanceOfCommunicationTimestampsDTO = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the CommunicationTimestampsDTO interface.
 */
function instanceOfCommunicationTimestampsDTO(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfCommunicationTimestampsDTO = instanceOfCommunicationTimestampsDTO;
function CommunicationTimestampsDTOFromJSON(json) {
    return CommunicationTimestampsDTOFromJSONTyped(json, false);
}
exports.CommunicationTimestampsDTOFromJSON = CommunicationTimestampsDTOFromJSON;
function CommunicationTimestampsDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'sendTimestamp': !(0, runtime_1.exists)(json, 'sendTimestamp') ? undefined : json['sendTimestamp'],
        'receiveTimestamp': !(0, runtime_1.exists)(json, 'receiveTimestamp') ? undefined : json['receiveTimestamp'],
    };
}
exports.CommunicationTimestampsDTOFromJSONTyped = CommunicationTimestampsDTOFromJSONTyped;
function CommunicationTimestampsDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'sendTimestamp': value.sendTimestamp,
        'receiveTimestamp': value.receiveTimestamp,
    };
}
exports.CommunicationTimestampsDTOToJSON = CommunicationTimestampsDTOToJSON;
