"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CosignatureToJSON = exports.CosignatureFromJSONTyped = exports.CosignatureFromJSON = exports.instanceOfCosignature = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Cosignature interface.
 */
function instanceOfCosignature(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfCosignature = instanceOfCosignature;
function CosignatureFromJSON(json) {
    return CosignatureFromJSONTyped(json, false);
}
exports.CosignatureFromJSON = CosignatureFromJSON;
function CosignatureFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'parentHash': !(0, runtime_1.exists)(json, 'parentHash') ? undefined : json['parentHash'],
        'signature': !(0, runtime_1.exists)(json, 'signature') ? undefined : json['signature'],
        'signerPublicKey': !(0, runtime_1.exists)(json, 'signerPublicKey') ? undefined : json['signerPublicKey'],
        'version': !(0, runtime_1.exists)(json, 'version') ? undefined : json['version'],
    };
}
exports.CosignatureFromJSONTyped = CosignatureFromJSONTyped;
function CosignatureToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'parentHash': value.parentHash,
        'signature': value.signature,
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
    };
}
exports.CosignatureToJSON = CosignatureToJSON;
