"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeploymentDTOToJSON = exports.DeploymentDTOFromJSONTyped = exports.DeploymentDTOFromJSON = exports.instanceOfDeploymentDTO = void 0;
/**
 * Check if a given object implements the DeploymentDTO interface.
 */
function instanceOfDeploymentDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "deploymentTool" in value;
    isInstance = isInstance && "deploymentToolVersion" in value;
    isInstance = isInstance && "lastUpdatedDate" in value;
    return isInstance;
}
exports.instanceOfDeploymentDTO = instanceOfDeploymentDTO;
function DeploymentDTOFromJSON(json) {
    return DeploymentDTOFromJSONTyped(json, false);
}
exports.DeploymentDTOFromJSON = DeploymentDTOFromJSON;
function DeploymentDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'deploymentTool': json['deploymentTool'],
        'deploymentToolVersion': json['deploymentToolVersion'],
        'lastUpdatedDate': json['lastUpdatedDate'],
    };
}
exports.DeploymentDTOFromJSONTyped = DeploymentDTOFromJSONTyped;
function DeploymentDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'deploymentTool': value.deploymentTool,
        'deploymentToolVersion': value.deploymentToolVersion,
        'lastUpdatedDate': value.lastUpdatedDate,
    };
}
exports.DeploymentDTOToJSON = DeploymentDTOToJSON;
