"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmbeddedMosaicGlobalRestrictionTransactionDTOToJSON = exports.EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSONTyped = exports.EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSON = exports.instanceOfEmbeddedMosaicGlobalRestrictionTransactionDTO = void 0;
const MosaicRestrictionTypeEnum_1 = require("./MosaicRestrictionTypeEnum");
const NetworkTypeEnum_1 = require("./NetworkTypeEnum");
/**
 * Check if a given object implements the EmbeddedMosaicGlobalRestrictionTransactionDTO interface.
 */
function instanceOfEmbeddedMosaicGlobalRestrictionTransactionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "signerPublicKey" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "network" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "referenceMosaicId" in value;
    isInstance = isInstance && "restrictionKey" in value;
    isInstance = isInstance && "previousRestrictionValue" in value;
    isInstance = isInstance && "newRestrictionValue" in value;
    isInstance = isInstance && "previousRestrictionType" in value;
    isInstance = isInstance && "newRestrictionType" in value;
    return isInstance;
}
exports.instanceOfEmbeddedMosaicGlobalRestrictionTransactionDTO = instanceOfEmbeddedMosaicGlobalRestrictionTransactionDTO;
function EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSON(json) {
    return EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSONTyped(json, false);
}
exports.EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSON = EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSON;
function EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        signerPublicKey: json["signerPublicKey"],
        version: json["version"],
        network: (0, NetworkTypeEnum_1.NetworkTypeEnumFromJSON)(json["network"]),
        type: json["type"],
        mosaicId: json["mosaicId"],
        referenceMosaicId: json["referenceMosaicId"],
        restrictionKey: json["restrictionKey"],
        previousRestrictionValue: json["previousRestrictionValue"],
        newRestrictionValue: json["newRestrictionValue"],
        previousRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumFromJSON)(json["previousRestrictionType"]),
        newRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumFromJSON)(json["newRestrictionType"]),
    };
}
exports.EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSONTyped = EmbeddedMosaicGlobalRestrictionTransactionDTOFromJSONTyped;
function EmbeddedMosaicGlobalRestrictionTransactionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        signerPublicKey: value.signerPublicKey,
        version: value.version,
        network: (0, NetworkTypeEnum_1.NetworkTypeEnumToJSON)(value.network),
        type: value.type,
        mosaicId: value.mosaicId,
        referenceMosaicId: value.referenceMosaicId,
        restrictionKey: value.restrictionKey,
        previousRestrictionValue: value.previousRestrictionValue,
        newRestrictionValue: value.newRestrictionValue,
        previousRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumToJSON)(value.previousRestrictionType),
        newRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumToJSON)(value.newRestrictionType),
    };
}
exports.EmbeddedMosaicGlobalRestrictionTransactionDTOToJSON = EmbeddedMosaicGlobalRestrictionTransactionDTOToJSON;
