"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmbeddedMosaicAliasTransactionDTOToJSON = exports.EmbeddedMosaicAliasTransactionDTOFromJSONTyped = exports.EmbeddedMosaicAliasTransactionDTOFromJSON = exports.instanceOfEmbeddedMosaicAliasTransactionDTO = void 0;
const AliasActionEnum_1 = require("./AliasActionEnum");
const NetworkTypeEnum_1 = require("./NetworkTypeEnum");
/**
 * Check if a given object implements the EmbeddedMosaicAliasTransactionDTO interface.
 */
function instanceOfEmbeddedMosaicAliasTransactionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "signerPublicKey" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "network" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "namespaceId" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "aliasAction" in value;
    return isInstance;
}
exports.instanceOfEmbeddedMosaicAliasTransactionDTO = instanceOfEmbeddedMosaicAliasTransactionDTO;
function EmbeddedMosaicAliasTransactionDTOFromJSON(json) {
    return EmbeddedMosaicAliasTransactionDTOFromJSONTyped(json, false);
}
exports.EmbeddedMosaicAliasTransactionDTOFromJSON = EmbeddedMosaicAliasTransactionDTOFromJSON;
function EmbeddedMosaicAliasTransactionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumFromJSON)(json['network']),
        'type': json['type'],
        'namespaceId': json['namespaceId'],
        'mosaicId': json['mosaicId'],
        'aliasAction': (0, AliasActionEnum_1.AliasActionEnumFromJSON)(json['aliasAction']),
    };
}
exports.EmbeddedMosaicAliasTransactionDTOFromJSONTyped = EmbeddedMosaicAliasTransactionDTOFromJSONTyped;
function EmbeddedMosaicAliasTransactionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumToJSON)(value.network),
        'type': value.type,
        'namespaceId': value.namespaceId,
        'mosaicId': value.mosaicId,
        'aliasAction': (0, AliasActionEnum_1.AliasActionEnumToJSON)(value.aliasAction),
    };
}
exports.EmbeddedMosaicAliasTransactionDTOToJSON = EmbeddedMosaicAliasTransactionDTOToJSON;
