"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmbeddedTransactionMetaDTOToJSON = exports.EmbeddedTransactionMetaDTOFromJSONTyped = exports.EmbeddedTransactionMetaDTOFromJSON = exports.instanceOfEmbeddedTransactionMetaDTO = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the EmbeddedTransactionMetaDTO interface.
 */
function instanceOfEmbeddedTransactionMetaDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "aggregateHash" in value;
    isInstance = isInstance && "aggregateId" in value;
    isInstance = isInstance && "index" in value;
    return isInstance;
}
exports.instanceOfEmbeddedTransactionMetaDTO = instanceOfEmbeddedTransactionMetaDTO;
function EmbeddedTransactionMetaDTOFromJSON(json) {
    return EmbeddedTransactionMetaDTOFromJSONTyped(json, false);
}
exports.EmbeddedTransactionMetaDTOFromJSON = EmbeddedTransactionMetaDTOFromJSON;
function EmbeddedTransactionMetaDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'height': json['height'],
        'aggregateHash': json['aggregateHash'],
        'aggregateId': json['aggregateId'],
        'index': json['index'],
        'timestamp': !(0, runtime_1.exists)(json, 'timestamp') ? undefined : json['timestamp'],
        'feeMultiplier': !(0, runtime_1.exists)(json, 'feeMultiplier') ? undefined : json['feeMultiplier'],
    };
}
exports.EmbeddedTransactionMetaDTOFromJSONTyped = EmbeddedTransactionMetaDTOFromJSONTyped;
function EmbeddedTransactionMetaDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'height': value.height,
        'aggregateHash': value.aggregateHash,
        'aggregateId': value.aggregateId,
        'index': value.index,
        'timestamp': value.timestamp,
        'feeMultiplier': value.feeMultiplier,
    };
}
exports.EmbeddedTransactionMetaDTOToJSON = EmbeddedTransactionMetaDTOToJSON;
