"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmbeddedAccountAddressRestrictionTransactionDTOToJSON = exports.EmbeddedAccountAddressRestrictionTransactionDTOFromJSONTyped = exports.EmbeddedAccountAddressRestrictionTransactionDTOFromJSON = exports.instanceOfEmbeddedAccountAddressRestrictionTransactionDTO = void 0;
const runtime_1 = require("../runtime");
const AccountRestrictionFlagsEnum_1 = require("./AccountRestrictionFlagsEnum");
const NetworkTypeEnum_1 = require("./NetworkTypeEnum");
/**
 * Check if a given object implements the EmbeddedAccountAddressRestrictionTransactionDTO interface.
 */
function instanceOfEmbeddedAccountAddressRestrictionTransactionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "signerPublicKey" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "network" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "restrictionFlags" in value;
    return isInstance;
}
exports.instanceOfEmbeddedAccountAddressRestrictionTransactionDTO = instanceOfEmbeddedAccountAddressRestrictionTransactionDTO;
function EmbeddedAccountAddressRestrictionTransactionDTOFromJSON(json) {
    return EmbeddedAccountAddressRestrictionTransactionDTOFromJSONTyped(json, false);
}
exports.EmbeddedAccountAddressRestrictionTransactionDTOFromJSON = EmbeddedAccountAddressRestrictionTransactionDTOFromJSON;
function EmbeddedAccountAddressRestrictionTransactionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumFromJSON)(json['network']),
        'type': json['type'],
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumFromJSON)(json['restrictionFlags']),
        'restrictionAdditions': !(0, runtime_1.exists)(json, 'restrictionAdditions') ? undefined : json['restrictionAdditions'],
        'restrictionDeletions': !(0, runtime_1.exists)(json, 'restrictionDeletions') ? undefined : json['restrictionDeletions'],
    };
}
exports.EmbeddedAccountAddressRestrictionTransactionDTOFromJSONTyped = EmbeddedAccountAddressRestrictionTransactionDTOFromJSONTyped;
function EmbeddedAccountAddressRestrictionTransactionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumToJSON)(value.network),
        'type': value.type,
        'restrictionFlags': (0, AccountRestrictionFlagsEnum_1.AccountRestrictionFlagsEnumToJSON)(value.restrictionFlags),
        'restrictionAdditions': value.restrictionAdditions,
        'restrictionDeletions': value.restrictionDeletions,
    };
}
exports.EmbeddedAccountAddressRestrictionTransactionDTOToJSON = EmbeddedAccountAddressRestrictionTransactionDTOToJSON;
