"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HashLockEntryDTOToJSON = exports.HashLockEntryDTOFromJSONTyped = exports.HashLockEntryDTOFromJSON = exports.instanceOfHashLockEntryDTO = void 0;
const LockStatus_1 = require("./LockStatus");
/**
 * Check if a given object implements the HashLockEntryDTO interface.
 */
function instanceOfHashLockEntryDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "ownerAddress" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "endHeight" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "hash" in value;
    return isInstance;
}
exports.instanceOfHashLockEntryDTO = instanceOfHashLockEntryDTO;
function HashLockEntryDTOFromJSON(json) {
    return HashLockEntryDTOFromJSONTyped(json, false);
}
exports.HashLockEntryDTOFromJSON = HashLockEntryDTOFromJSON;
function HashLockEntryDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'version': json['version'],
        'ownerAddress': json['ownerAddress'],
        'mosaicId': json['mosaicId'],
        'amount': json['amount'],
        'endHeight': json['endHeight'],
        'status': (0, LockStatus_1.LockStatusFromJSON)(json['status']),
        'hash': json['hash'],
    };
}
exports.HashLockEntryDTOFromJSONTyped = HashLockEntryDTOFromJSONTyped;
function HashLockEntryDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'version': value.version,
        'ownerAddress': value.ownerAddress,
        'mosaicId': value.mosaicId,
        'amount': value.amount,
        'endHeight': value.endHeight,
        'status': (0, LockStatus_1.LockStatusToJSON)(value.status),
        'hash': value.hash,
    };
}
exports.HashLockEntryDTOToJSON = HashLockEntryDTOToJSON;
