"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinkActionEnumToJSON = exports.LinkActionEnumFromJSONTyped = exports.LinkActionEnumFromJSON = exports.LinkActionEnum = void 0;
/**
 * Type of action:
 * * 0 - Unlink.
 * * 1 - Link.
 * @export
 */
exports.LinkActionEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
};
function LinkActionEnumFromJSON(json) {
    return LinkActionEnumFromJSONTyped(json, false);
}
exports.LinkActionEnumFromJSON = LinkActionEnumFromJSON;
function LinkActionEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.LinkActionEnumFromJSONTyped = LinkActionEnumFromJSONTyped;
function LinkActionEnumToJSON(value) {
    return value;
}
exports.LinkActionEnumToJSON = LinkActionEnumToJSON;
