"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MerkleStateInfoDTOToJSON = exports.MerkleStateInfoDTOFromJSONTyped = exports.MerkleStateInfoDTOFromJSON = exports.instanceOfMerkleStateInfoDTO = void 0;
const MerkleStateInfoDTOTreeInner_1 = require("./MerkleStateInfoDTOTreeInner");
/**
 * Check if a given object implements the MerkleStateInfoDTO interface.
 */
function instanceOfMerkleStateInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "raw" in value;
    isInstance = isInstance && "tree" in value;
    return isInstance;
}
exports.instanceOfMerkleStateInfoDTO = instanceOfMerkleStateInfoDTO;
function MerkleStateInfoDTOFromJSON(json) {
    return MerkleStateInfoDTOFromJSONTyped(json, false);
}
exports.MerkleStateInfoDTOFromJSON = MerkleStateInfoDTOFromJSON;
function MerkleStateInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'raw': json['raw'],
        'tree': (json['tree'].map(MerkleStateInfoDTOTreeInner_1.MerkleStateInfoDTOTreeInnerFromJSON)),
    };
}
exports.MerkleStateInfoDTOFromJSONTyped = MerkleStateInfoDTOFromJSONTyped;
function MerkleStateInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'raw': value.raw,
        'tree': (value.tree.map(MerkleStateInfoDTOTreeInner_1.MerkleStateInfoDTOTreeInnerToJSON)),
    };
}
exports.MerkleStateInfoDTOToJSON = MerkleStateInfoDTOToJSON;
