"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetadataPageToJSON = exports.MetadataPageFromJSONTyped = exports.MetadataPageFromJSON = exports.instanceOfMetadataPage = void 0;
const MetadataInfoDTO_1 = require("./MetadataInfoDTO");
const Pagination_1 = require("./Pagination");
/**
 * Check if a given object implements the MetadataPage interface.
 */
function instanceOfMetadataPage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfMetadataPage = instanceOfMetadataPage;
function MetadataPageFromJSON(json) {
    return MetadataPageFromJSONTyped(json, false);
}
exports.MetadataPageFromJSON = MetadataPageFromJSON;
function MetadataPageFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': (json['data'].map(MetadataInfoDTO_1.MetadataInfoDTOFromJSON)),
        'pagination': (0, Pagination_1.PaginationFromJSON)(json['pagination']),
    };
}
exports.MetadataPageFromJSONTyped = MetadataPageFromJSONTyped;
function MetadataPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (value.data.map(MetadataInfoDTO_1.MetadataInfoDTOToJSON)),
        'pagination': (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.MetadataPageToJSON = MetadataPageToJSON;
