"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetadataInfoDTOToJSON = exports.MetadataInfoDTOFromJSONTyped = exports.MetadataInfoDTOFromJSON = exports.instanceOfMetadataInfoDTO = void 0;
const MetadataEntryDTO_1 = require("./MetadataEntryDTO");
/**
 * Check if a given object implements the MetadataInfoDTO interface.
 */
function instanceOfMetadataInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "metadataEntry" in value;
    return isInstance;
}
exports.instanceOfMetadataInfoDTO = instanceOfMetadataInfoDTO;
function MetadataInfoDTOFromJSON(json) {
    return MetadataInfoDTOFromJSONTyped(json, false);
}
exports.MetadataInfoDTOFromJSON = MetadataInfoDTOFromJSON;
function MetadataInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json["id"],
        metadataEntry: (0, MetadataEntryDTO_1.MetadataEntryDTOFromJSON)(json["metadataEntry"]),
    };
}
exports.MetadataInfoDTOFromJSONTyped = MetadataInfoDTOFromJSONTyped;
function MetadataInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        metadataEntry: (0, MetadataEntryDTO_1.MetadataEntryDTOToJSON)(value.metadataEntry),
    };
}
exports.MetadataInfoDTOToJSON = MetadataInfoDTOToJSON;
