"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetadataTypeEnumToJSON = exports.MetadataTypeEnumFromJSONTyped = exports.MetadataTypeEnumFromJSON = exports.MetadataTypeEnum = void 0;
/**
 * Metadata type:
 * * 0 - Account.
 * * 1 - Mosaic.
 * * 2 - Namespace.
 * @export
 */
exports.MetadataTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
};
function MetadataTypeEnumFromJSON(json) {
    return MetadataTypeEnumFromJSONTyped(json, false);
}
exports.MetadataTypeEnumFromJSON = MetadataTypeEnumFromJSON;
function MetadataTypeEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.MetadataTypeEnumFromJSONTyped = MetadataTypeEnumFromJSONTyped;
function MetadataTypeEnumToJSON(value) {
    return value;
}
exports.MetadataTypeEnumToJSON = MetadataTypeEnumToJSON;
