"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetadataNetworkPropertiesDTOToJSON = exports.MetadataNetworkPropertiesDTOFromJSONTyped = exports.MetadataNetworkPropertiesDTOFromJSON = exports.instanceOfMetadataNetworkPropertiesDTO = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the MetadataNetworkPropertiesDTO interface.
 */
function instanceOfMetadataNetworkPropertiesDTO(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfMetadataNetworkPropertiesDTO = instanceOfMetadataNetworkPropertiesDTO;
function MetadataNetworkPropertiesDTOFromJSON(json) {
    return MetadataNetworkPropertiesDTOFromJSONTyped(json, false);
}
exports.MetadataNetworkPropertiesDTOFromJSON = MetadataNetworkPropertiesDTOFromJSON;
function MetadataNetworkPropertiesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'maxValueSize': !(0, runtime_1.exists)(json, 'maxValueSize') ? undefined : json['maxValueSize'],
    };
}
exports.MetadataNetworkPropertiesDTOFromJSONTyped = MetadataNetworkPropertiesDTOFromJSONTyped;
function MetadataNetworkPropertiesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'maxValueSize': value.maxValueSize,
    };
}
exports.MetadataNetworkPropertiesDTOToJSON = MetadataNetworkPropertiesDTOToJSON;
