"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetadataEntryDTOTargetIdToJSON = exports.MetadataEntryDTOTargetIdFromJSONTyped = exports.MetadataEntryDTOTargetIdFromJSON = exports.instanceOfMetadataEntryDTOTargetId = void 0;
/**
 * Check if a given object implements the MetadataEntryDTOTargetId interface.
 */
function instanceOfMetadataEntryDTOTargetId(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfMetadataEntryDTOTargetId = instanceOfMetadataEntryDTOTargetId;
function MetadataEntryDTOTargetIdFromJSON(json) {
    return MetadataEntryDTOTargetIdFromJSONTyped(json, false);
}
exports.MetadataEntryDTOTargetIdFromJSON = MetadataEntryDTOTargetIdFromJSON;
function MetadataEntryDTOTargetIdFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.MetadataEntryDTOTargetIdFromJSONTyped = MetadataEntryDTOTargetIdFromJSONTyped;
function MetadataEntryDTOTargetIdToJSON(value) {
    return value;
}
exports.MetadataEntryDTOTargetIdToJSON = MetadataEntryDTOTargetIdToJSON;
