"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicAddressRestrictionEntryWrapperDTOToJSON = exports.MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped = exports.MosaicAddressRestrictionEntryWrapperDTOFromJSON = exports.instanceOfMosaicAddressRestrictionEntryWrapperDTO = void 0;
const MosaicAddressRestrictionEntryDTO_1 = require("./MosaicAddressRestrictionEntryDTO");
const MosaicRestrictionEntryTypeEnum_1 = require("./MosaicRestrictionEntryTypeEnum");
/**
 * Check if a given object implements the MosaicAddressRestrictionEntryWrapperDTO interface.
 */
function instanceOfMosaicAddressRestrictionEntryWrapperDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "compositeHash" in value;
    isInstance = isInstance && "entryType" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "targetAddress" in value;
    isInstance = isInstance && "restrictions" in value;
    return isInstance;
}
exports.instanceOfMosaicAddressRestrictionEntryWrapperDTO = instanceOfMosaicAddressRestrictionEntryWrapperDTO;
function MosaicAddressRestrictionEntryWrapperDTOFromJSON(json) {
    return MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped(json, false);
}
exports.MosaicAddressRestrictionEntryWrapperDTOFromJSON = MosaicAddressRestrictionEntryWrapperDTOFromJSON;
function MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        version: json["version"],
        compositeHash: json["compositeHash"],
        entryType: (0, MosaicRestrictionEntryTypeEnum_1.MosaicRestrictionEntryTypeEnumFromJSON)(json["entryType"]),
        mosaicId: json["mosaicId"],
        targetAddress: json["targetAddress"],
        restrictions: json["restrictions"].map(MosaicAddressRestrictionEntryDTO_1.MosaicAddressRestrictionEntryDTOFromJSON),
    };
}
exports.MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped = MosaicAddressRestrictionEntryWrapperDTOFromJSONTyped;
function MosaicAddressRestrictionEntryWrapperDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        version: value.version,
        compositeHash: value.compositeHash,
        entryType: (0, MosaicRestrictionEntryTypeEnum_1.MosaicRestrictionEntryTypeEnumToJSON)(value.entryType),
        mosaicId: value.mosaicId,
        targetAddress: value.targetAddress,
        restrictions: value.restrictions.map(MosaicAddressRestrictionEntryDTO_1.MosaicAddressRestrictionEntryDTOToJSON),
    };
}
exports.MosaicAddressRestrictionEntryWrapperDTOToJSON = MosaicAddressRestrictionEntryWrapperDTOToJSON;
