"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicGlobalRestrictionEntryWrapperDTOToJSON = exports.MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped = exports.MosaicGlobalRestrictionEntryWrapperDTOFromJSON = exports.instanceOfMosaicGlobalRestrictionEntryWrapperDTO = void 0;
const MosaicGlobalRestrictionEntryDTO_1 = require("./MosaicGlobalRestrictionEntryDTO");
const MosaicRestrictionEntryTypeEnum_1 = require("./MosaicRestrictionEntryTypeEnum");
/**
 * Check if a given object implements the MosaicGlobalRestrictionEntryWrapperDTO interface.
 */
function instanceOfMosaicGlobalRestrictionEntryWrapperDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "compositeHash" in value;
    isInstance = isInstance && "entryType" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "restrictions" in value;
    return isInstance;
}
exports.instanceOfMosaicGlobalRestrictionEntryWrapperDTO = instanceOfMosaicGlobalRestrictionEntryWrapperDTO;
function MosaicGlobalRestrictionEntryWrapperDTOFromJSON(json) {
    return MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped(json, false);
}
exports.MosaicGlobalRestrictionEntryWrapperDTOFromJSON = MosaicGlobalRestrictionEntryWrapperDTOFromJSON;
function MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'version': json['version'],
        'compositeHash': json['compositeHash'],
        'entryType': (0, MosaicRestrictionEntryTypeEnum_1.MosaicRestrictionEntryTypeEnumFromJSON)(json['entryType']),
        'mosaicId': json['mosaicId'],
        'restrictions': (json['restrictions'].map(MosaicGlobalRestrictionEntryDTO_1.MosaicGlobalRestrictionEntryDTOFromJSON)),
    };
}
exports.MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped = MosaicGlobalRestrictionEntryWrapperDTOFromJSONTyped;
function MosaicGlobalRestrictionEntryWrapperDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'version': value.version,
        'compositeHash': value.compositeHash,
        'entryType': (0, MosaicRestrictionEntryTypeEnum_1.MosaicRestrictionEntryTypeEnumToJSON)(value.entryType),
        'mosaicId': value.mosaicId,
        'restrictions': (value.restrictions.map(MosaicGlobalRestrictionEntryDTO_1.MosaicGlobalRestrictionEntryDTOToJSON)),
    };
}
exports.MosaicGlobalRestrictionEntryWrapperDTOToJSON = MosaicGlobalRestrictionEntryWrapperDTOToJSON;
