"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicGlobalRestrictionTransactionBodyDTOToJSON = exports.MosaicGlobalRestrictionTransactionBodyDTOFromJSONTyped = exports.MosaicGlobalRestrictionTransactionBodyDTOFromJSON = exports.instanceOfMosaicGlobalRestrictionTransactionBodyDTO = void 0;
const MosaicRestrictionTypeEnum_1 = require("./MosaicRestrictionTypeEnum");
/**
 * Check if a given object implements the MosaicGlobalRestrictionTransactionBodyDTO interface.
 */
function instanceOfMosaicGlobalRestrictionTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "referenceMosaicId" in value;
    isInstance = isInstance && "restrictionKey" in value;
    isInstance = isInstance && "previousRestrictionValue" in value;
    isInstance = isInstance && "newRestrictionValue" in value;
    isInstance = isInstance && "previousRestrictionType" in value;
    isInstance = isInstance && "newRestrictionType" in value;
    return isInstance;
}
exports.instanceOfMosaicGlobalRestrictionTransactionBodyDTO = instanceOfMosaicGlobalRestrictionTransactionBodyDTO;
function MosaicGlobalRestrictionTransactionBodyDTOFromJSON(json) {
    return MosaicGlobalRestrictionTransactionBodyDTOFromJSONTyped(json, false);
}
exports.MosaicGlobalRestrictionTransactionBodyDTOFromJSON = MosaicGlobalRestrictionTransactionBodyDTOFromJSON;
function MosaicGlobalRestrictionTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        mosaicId: json["mosaicId"],
        referenceMosaicId: json["referenceMosaicId"],
        restrictionKey: json["restrictionKey"],
        previousRestrictionValue: json["previousRestrictionValue"],
        newRestrictionValue: json["newRestrictionValue"],
        previousRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumFromJSON)(json["previousRestrictionType"]),
        newRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumFromJSON)(json["newRestrictionType"]),
    };
}
exports.MosaicGlobalRestrictionTransactionBodyDTOFromJSONTyped = MosaicGlobalRestrictionTransactionBodyDTOFromJSONTyped;
function MosaicGlobalRestrictionTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        mosaicId: value.mosaicId,
        referenceMosaicId: value.referenceMosaicId,
        restrictionKey: value.restrictionKey,
        previousRestrictionValue: value.previousRestrictionValue,
        newRestrictionValue: value.newRestrictionValue,
        previousRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumToJSON)(value.previousRestrictionType),
        newRestrictionType: (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumToJSON)(value.newRestrictionType),
    };
}
exports.MosaicGlobalRestrictionTransactionBodyDTOToJSON = MosaicGlobalRestrictionTransactionBodyDTOToJSON;
