"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicRestrictionsPageToJSON = exports.MosaicRestrictionsPageFromJSONTyped = exports.MosaicRestrictionsPageFromJSON = exports.instanceOfMosaicRestrictionsPage = void 0;
const MosaicRestrictionsPageDataInner_1 = require("./MosaicRestrictionsPageDataInner");
const Pagination_1 = require("./Pagination");
/**
 * Check if a given object implements the MosaicRestrictionsPage interface.
 */
function instanceOfMosaicRestrictionsPage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfMosaicRestrictionsPage = instanceOfMosaicRestrictionsPage;
function MosaicRestrictionsPageFromJSON(json) {
    return MosaicRestrictionsPageFromJSONTyped(json, false);
}
exports.MosaicRestrictionsPageFromJSON = MosaicRestrictionsPageFromJSON;
function MosaicRestrictionsPageFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': (json['data'].map(MosaicRestrictionsPageDataInner_1.MosaicRestrictionsPageDataInnerFromJSON)),
        'pagination': (0, Pagination_1.PaginationFromJSON)(json['pagination']),
    };
}
exports.MosaicRestrictionsPageFromJSONTyped = MosaicRestrictionsPageFromJSONTyped;
function MosaicRestrictionsPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (value.data.map(MosaicRestrictionsPageDataInner_1.MosaicRestrictionsPageDataInnerToJSON)),
        'pagination': (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.MosaicRestrictionsPageToJSON = MosaicRestrictionsPageToJSON;
