"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicRestrictionEntryTypeEnumToJSON = exports.MosaicRestrictionEntryTypeEnumFromJSONTyped = exports.MosaicRestrictionEntryTypeEnumFromJSON = exports.MosaicRestrictionEntryTypeEnum = void 0;
/**
 * - 0 - Mosaic address restriction.
 * - 1 - Mosaic global restriction.
 * @export
 */
exports.MosaicRestrictionEntryTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
};
function MosaicRestrictionEntryTypeEnumFromJSON(json) {
    return MosaicRestrictionEntryTypeEnumFromJSONTyped(json, false);
}
exports.MosaicRestrictionEntryTypeEnumFromJSON = MosaicRestrictionEntryTypeEnumFromJSON;
function MosaicRestrictionEntryTypeEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.MosaicRestrictionEntryTypeEnumFromJSONTyped = MosaicRestrictionEntryTypeEnumFromJSONTyped;
function MosaicRestrictionEntryTypeEnumToJSON(value) {
    return value;
}
exports.MosaicRestrictionEntryTypeEnumToJSON = MosaicRestrictionEntryTypeEnumToJSON;
