"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicExpiryReceiptDTOAllOfToJSON = exports.MosaicExpiryReceiptDTOAllOfFromJSONTyped = exports.MosaicExpiryReceiptDTOAllOfFromJSON = exports.instanceOfMosaicExpiryReceiptDTOAllOf = void 0;
/**
 * Check if a given object implements the MosaicExpiryReceiptDTOAllOf interface.
 */
function instanceOfMosaicExpiryReceiptDTOAllOf(value) {
    let isInstance = true;
    isInstance = isInstance && "artifactId" in value;
    return isInstance;
}
exports.instanceOfMosaicExpiryReceiptDTOAllOf = instanceOfMosaicExpiryReceiptDTOAllOf;
function MosaicExpiryReceiptDTOAllOfFromJSON(json) {
    return MosaicExpiryReceiptDTOAllOfFromJSONTyped(json, false);
}
exports.MosaicExpiryReceiptDTOAllOfFromJSON = MosaicExpiryReceiptDTOAllOfFromJSON;
function MosaicExpiryReceiptDTOAllOfFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'artifactId': json['artifactId'],
    };
}
exports.MosaicExpiryReceiptDTOAllOfFromJSONTyped = MosaicExpiryReceiptDTOAllOfFromJSONTyped;
function MosaicExpiryReceiptDTOAllOfToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'artifactId': value.artifactId,
    };
}
exports.MosaicExpiryReceiptDTOAllOfToJSON = MosaicExpiryReceiptDTOAllOfToJSON;
