"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicSupplyChangeTransactionDTOToJSON = exports.MosaicSupplyChangeTransactionDTOFromJSONTyped = exports.MosaicSupplyChangeTransactionDTOFromJSON = exports.instanceOfMosaicSupplyChangeTransactionDTO = void 0;
const MosaicSupplyChangeActionEnum_1 = require("./MosaicSupplyChangeActionEnum");
const NetworkTypeEnum_1 = require("./NetworkTypeEnum");
/**
 * Check if a given object implements the MosaicSupplyChangeTransactionDTO interface.
 */
function instanceOfMosaicSupplyChangeTransactionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "signature" in value;
    isInstance = isInstance && "signerPublicKey" in value;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "network" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "maxFee" in value;
    isInstance = isInstance && "deadline" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "delta" in value;
    isInstance = isInstance && "action" in value;
    return isInstance;
}
exports.instanceOfMosaicSupplyChangeTransactionDTO = instanceOfMosaicSupplyChangeTransactionDTO;
function MosaicSupplyChangeTransactionDTOFromJSON(json) {
    return MosaicSupplyChangeTransactionDTOFromJSONTyped(json, false);
}
exports.MosaicSupplyChangeTransactionDTOFromJSON = MosaicSupplyChangeTransactionDTOFromJSON;
function MosaicSupplyChangeTransactionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'size': json['size'],
        'signature': json['signature'],
        'signerPublicKey': json['signerPublicKey'],
        'version': json['version'],
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumFromJSON)(json['network']),
        'type': json['type'],
        'maxFee': json['maxFee'],
        'deadline': json['deadline'],
        'mosaicId': json['mosaicId'],
        'delta': json['delta'],
        'action': (0, MosaicSupplyChangeActionEnum_1.MosaicSupplyChangeActionEnumFromJSON)(json['action']),
    };
}
exports.MosaicSupplyChangeTransactionDTOFromJSONTyped = MosaicSupplyChangeTransactionDTOFromJSONTyped;
function MosaicSupplyChangeTransactionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'size': value.size,
        'signature': value.signature,
        'signerPublicKey': value.signerPublicKey,
        'version': value.version,
        'network': (0, NetworkTypeEnum_1.NetworkTypeEnumToJSON)(value.network),
        'type': value.type,
        'maxFee': value.maxFee,
        'deadline': value.deadline,
        'mosaicId': value.mosaicId,
        'delta': value.delta,
        'action': (0, MosaicSupplyChangeActionEnum_1.MosaicSupplyChangeActionEnumToJSON)(value.action),
    };
}
exports.MosaicSupplyChangeTransactionDTOToJSON = MosaicSupplyChangeTransactionDTOToJSON;
