"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicExpiryReceiptDTOToJSON = exports.MosaicExpiryReceiptDTOFromJSONTyped = exports.MosaicExpiryReceiptDTOFromJSON = exports.instanceOfMosaicExpiryReceiptDTO = void 0;
const ReceiptTypeEnum_1 = require("./ReceiptTypeEnum");
/**
 * Check if a given object implements the MosaicExpiryReceiptDTO interface.
 */
function instanceOfMosaicExpiryReceiptDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "artifactId" in value;
    return isInstance;
}
exports.instanceOfMosaicExpiryReceiptDTO = instanceOfMosaicExpiryReceiptDTO;
function MosaicExpiryReceiptDTOFromJSON(json) {
    return MosaicExpiryReceiptDTOFromJSONTyped(json, false);
}
exports.MosaicExpiryReceiptDTOFromJSON = MosaicExpiryReceiptDTOFromJSON;
function MosaicExpiryReceiptDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'version': json['version'],
        'type': (0, ReceiptTypeEnum_1.ReceiptTypeEnumFromJSON)(json['type']),
        'artifactId': json['artifactId'],
    };
}
exports.MosaicExpiryReceiptDTOFromJSONTyped = MosaicExpiryReceiptDTOFromJSONTyped;
function MosaicExpiryReceiptDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'version': value.version,
        'type': (0, ReceiptTypeEnum_1.ReceiptTypeEnumToJSON)(value.type),
        'artifactId': value.artifactId,
    };
}
exports.MosaicExpiryReceiptDTOToJSON = MosaicExpiryReceiptDTOToJSON;
