"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicPageToJSON = exports.MosaicPageFromJSONTyped = exports.MosaicPageFromJSON = exports.instanceOfMosaicPage = void 0;
const MosaicInfoDTO_1 = require("./MosaicInfoDTO");
const Pagination_1 = require("./Pagination");
/**
 * Check if a given object implements the MosaicPage interface.
 */
function instanceOfMosaicPage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfMosaicPage = instanceOfMosaicPage;
function MosaicPageFromJSON(json) {
    return MosaicPageFromJSONTyped(json, false);
}
exports.MosaicPageFromJSON = MosaicPageFromJSON;
function MosaicPageFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': (json['data'].map(MosaicInfoDTO_1.MosaicInfoDTOFromJSON)),
        'pagination': (0, Pagination_1.PaginationFromJSON)(json['pagination']),
    };
}
exports.MosaicPageFromJSONTyped = MosaicPageFromJSONTyped;
function MosaicPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (value.data.map(MosaicInfoDTO_1.MosaicInfoDTOToJSON)),
        'pagination': (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.MosaicPageToJSON = MosaicPageToJSON;
