"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicGlobalRestrictionEntryRestrictionDTOToJSON = exports.MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped = exports.MosaicGlobalRestrictionEntryRestrictionDTOFromJSON = exports.instanceOfMosaicGlobalRestrictionEntryRestrictionDTO = void 0;
const MosaicRestrictionTypeEnum_1 = require("./MosaicRestrictionTypeEnum");
/**
 * Check if a given object implements the MosaicGlobalRestrictionEntryRestrictionDTO interface.
 */
function instanceOfMosaicGlobalRestrictionEntryRestrictionDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "referenceMosaicId" in value;
    isInstance = isInstance && "restrictionValue" in value;
    isInstance = isInstance && "restrictionType" in value;
    return isInstance;
}
exports.instanceOfMosaicGlobalRestrictionEntryRestrictionDTO = instanceOfMosaicGlobalRestrictionEntryRestrictionDTO;
function MosaicGlobalRestrictionEntryRestrictionDTOFromJSON(json) {
    return MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped(json, false);
}
exports.MosaicGlobalRestrictionEntryRestrictionDTOFromJSON = MosaicGlobalRestrictionEntryRestrictionDTOFromJSON;
function MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'referenceMosaicId': json['referenceMosaicId'],
        'restrictionValue': json['restrictionValue'],
        'restrictionType': (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumFromJSON)(json['restrictionType']),
    };
}
exports.MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped = MosaicGlobalRestrictionEntryRestrictionDTOFromJSONTyped;
function MosaicGlobalRestrictionEntryRestrictionDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'referenceMosaicId': value.referenceMosaicId,
        'restrictionValue': value.restrictionValue,
        'restrictionType': (0, MosaicRestrictionTypeEnum_1.MosaicRestrictionTypeEnumToJSON)(value.restrictionType),
    };
}
exports.MosaicGlobalRestrictionEntryRestrictionDTOToJSON = MosaicGlobalRestrictionEntryRestrictionDTOToJSON;
