"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicSupplyRevocationTransactionBodyDTOToJSON = exports.MosaicSupplyRevocationTransactionBodyDTOFromJSONTyped = exports.MosaicSupplyRevocationTransactionBodyDTOFromJSON = exports.instanceOfMosaicSupplyRevocationTransactionBodyDTO = void 0;
/**
 * Check if a given object implements the MosaicSupplyRevocationTransactionBodyDTO interface.
 */
function instanceOfMosaicSupplyRevocationTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "sourceAddress" in value;
    isInstance = isInstance && "mosaicId" in value;
    isInstance = isInstance && "amount" in value;
    return isInstance;
}
exports.instanceOfMosaicSupplyRevocationTransactionBodyDTO = instanceOfMosaicSupplyRevocationTransactionBodyDTO;
function MosaicSupplyRevocationTransactionBodyDTOFromJSON(json) {
    return MosaicSupplyRevocationTransactionBodyDTOFromJSONTyped(json, false);
}
exports.MosaicSupplyRevocationTransactionBodyDTOFromJSON = MosaicSupplyRevocationTransactionBodyDTOFromJSON;
function MosaicSupplyRevocationTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        sourceAddress: json["sourceAddress"],
        mosaicId: json["mosaicId"],
        amount: json["amount"],
    };
}
exports.MosaicSupplyRevocationTransactionBodyDTOFromJSONTyped = MosaicSupplyRevocationTransactionBodyDTOFromJSONTyped;
function MosaicSupplyRevocationTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        sourceAddress: value.sourceAddress,
        mosaicId: value.mosaicId,
        amount: value.amount,
    };
}
exports.MosaicSupplyRevocationTransactionBodyDTOToJSON = MosaicSupplyRevocationTransactionBodyDTOToJSON;
