"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicInfoDTOToJSON = exports.MosaicInfoDTOFromJSONTyped = exports.MosaicInfoDTOFromJSON = exports.instanceOfMosaicInfoDTO = void 0;
const MosaicDTO_1 = require("./MosaicDTO");
/**
 * Check if a given object implements the MosaicInfoDTO interface.
 */
function instanceOfMosaicInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "mosaic" in value;
    return isInstance;
}
exports.instanceOfMosaicInfoDTO = instanceOfMosaicInfoDTO;
function MosaicInfoDTOFromJSON(json) {
    return MosaicInfoDTOFromJSONTyped(json, false);
}
exports.MosaicInfoDTOFromJSON = MosaicInfoDTOFromJSON;
function MosaicInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json["id"],
        mosaic: (0, MosaicDTO_1.MosaicDTOFromJSON)(json["mosaic"]),
    };
}
exports.MosaicInfoDTOFromJSONTyped = MosaicInfoDTOFromJSONTyped;
function MosaicInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        mosaic: (0, MosaicDTO_1.MosaicDTOToJSON)(value.mosaic),
    };
}
exports.MosaicInfoDTOToJSON = MosaicInfoDTOToJSON;
