"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MosaicsNamesDTOToJSON = exports.MosaicsNamesDTOFromJSONTyped = exports.MosaicsNamesDTOFromJSON = exports.instanceOfMosaicsNamesDTO = void 0;
const MosaicNamesDTO_1 = require("./MosaicNamesDTO");
/**
 * Check if a given object implements the MosaicsNamesDTO interface.
 */
function instanceOfMosaicsNamesDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "mosaicNames" in value;
    return isInstance;
}
exports.instanceOfMosaicsNamesDTO = instanceOfMosaicsNamesDTO;
function MosaicsNamesDTOFromJSON(json) {
    return MosaicsNamesDTOFromJSONTyped(json, false);
}
exports.MosaicsNamesDTOFromJSON = MosaicsNamesDTOFromJSON;
function MosaicsNamesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        mosaicNames: json["mosaicNames"].map(MosaicNamesDTO_1.MosaicNamesDTOFromJSON),
    };
}
exports.MosaicsNamesDTOFromJSONTyped = MosaicsNamesDTOFromJSONTyped;
function MosaicsNamesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        mosaicNames: value.mosaicNames.map(MosaicNamesDTO_1.MosaicNamesDTOToJSON),
    };
}
exports.MosaicsNamesDTOToJSON = MosaicsNamesDTOToJSON;
