"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MultisigAccountInfoDTOToJSON = exports.MultisigAccountInfoDTOFromJSONTyped = exports.MultisigAccountInfoDTOFromJSON = exports.instanceOfMultisigAccountInfoDTO = void 0;
const MultisigDTO_1 = require("./MultisigDTO");
/**
 * Check if a given object implements the MultisigAccountInfoDTO interface.
 */
function instanceOfMultisigAccountInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "multisig" in value;
    return isInstance;
}
exports.instanceOfMultisigAccountInfoDTO = instanceOfMultisigAccountInfoDTO;
function MultisigAccountInfoDTOFromJSON(json) {
    return MultisigAccountInfoDTOFromJSONTyped(json, false);
}
exports.MultisigAccountInfoDTOFromJSON = MultisigAccountInfoDTOFromJSON;
function MultisigAccountInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        multisig: (0, MultisigDTO_1.MultisigDTOFromJSON)(json["multisig"]),
    };
}
exports.MultisigAccountInfoDTOFromJSONTyped = MultisigAccountInfoDTOFromJSONTyped;
function MultisigAccountInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        multisig: (0, MultisigDTO_1.MultisigDTOToJSON)(value.multisig),
    };
}
exports.MultisigAccountInfoDTOToJSON = MultisigAccountInfoDTOToJSON;
