"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NamespaceInfoDTOToJSON = exports.NamespaceInfoDTOFromJSONTyped = exports.NamespaceInfoDTOFromJSON = exports.instanceOfNamespaceInfoDTO = void 0;
const NamespaceDTO_1 = require("./NamespaceDTO");
const NamespaceMetaDTO_1 = require("./NamespaceMetaDTO");
/**
 * Check if a given object implements the NamespaceInfoDTO interface.
 */
function instanceOfNamespaceInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "namespace" in value;
    return isInstance;
}
exports.instanceOfNamespaceInfoDTO = instanceOfNamespaceInfoDTO;
function NamespaceInfoDTOFromJSON(json) {
    return NamespaceInfoDTOFromJSONTyped(json, false);
}
exports.NamespaceInfoDTOFromJSON = NamespaceInfoDTOFromJSON;
function NamespaceInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'meta': (0, NamespaceMetaDTO_1.NamespaceMetaDTOFromJSON)(json['meta']),
        'namespace': (0, NamespaceDTO_1.NamespaceDTOFromJSON)(json['namespace']),
    };
}
exports.NamespaceInfoDTOFromJSONTyped = NamespaceInfoDTOFromJSONTyped;
function NamespaceInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'meta': (0, NamespaceMetaDTO_1.NamespaceMetaDTOToJSON)(value.meta),
        'namespace': (0, NamespaceDTO_1.NamespaceDTOToJSON)(value.namespace),
    };
}
exports.NamespaceInfoDTOToJSON = NamespaceInfoDTOToJSON;
