"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NamespacePageToJSON = exports.NamespacePageFromJSONTyped = exports.NamespacePageFromJSON = exports.instanceOfNamespacePage = void 0;
const NamespaceInfoDTO_1 = require("./NamespaceInfoDTO");
const Pagination_1 = require("./Pagination");
/**
 * Check if a given object implements the NamespacePage interface.
 */
function instanceOfNamespacePage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfNamespacePage = instanceOfNamespacePage;
function NamespacePageFromJSON(json) {
    return NamespacePageFromJSONTyped(json, false);
}
exports.NamespacePageFromJSON = NamespacePageFromJSON;
function NamespacePageFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        data: json["data"].map(NamespaceInfoDTO_1.NamespaceInfoDTOFromJSON),
        pagination: (0, Pagination_1.PaginationFromJSON)(json["pagination"]),
    };
}
exports.NamespacePageFromJSONTyped = NamespacePageFromJSONTyped;
function NamespacePageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        data: value.data.map(NamespaceInfoDTO_1.NamespaceInfoDTOToJSON),
        pagination: (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.NamespacePageToJSON = NamespacePageToJSON;
