"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NetworkTypeDTOToJSON = exports.NetworkTypeDTOFromJSONTyped = exports.NetworkTypeDTOFromJSON = exports.instanceOfNetworkTypeDTO = void 0;
/**
 * Check if a given object implements the NetworkTypeDTO interface.
 */
function instanceOfNetworkTypeDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    return isInstance;
}
exports.instanceOfNetworkTypeDTO = instanceOfNetworkTypeDTO;
function NetworkTypeDTOFromJSON(json) {
    return NetworkTypeDTOFromJSONTyped(json, false);
}
exports.NetworkTypeDTOFromJSON = NetworkTypeDTOFromJSON;
function NetworkTypeDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"],
    };
}
exports.NetworkTypeDTOFromJSONTyped = NetworkTypeDTOFromJSONTyped;
function NetworkTypeDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        description: value.description,
    };
}
exports.NetworkTypeDTOToJSON = NetworkTypeDTOToJSON;
