"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeStatusEnumToJSON = exports.NodeStatusEnumFromJSONTyped = exports.NodeStatusEnumFromJSON = exports.NodeStatusEnum = void 0;
/**
 *
 * @export
 */
exports.NodeStatusEnum = {
    Up: 'up',
    Down: 'down'
};
function NodeStatusEnumFromJSON(json) {
    return NodeStatusEnumFromJSONTyped(json, false);
}
exports.NodeStatusEnumFromJSON = NodeStatusEnumFromJSON;
function NodeStatusEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.NodeStatusEnumFromJSONTyped = NodeStatusEnumFromJSONTyped;
function NodeStatusEnumToJSON(value) {
    return value;
}
exports.NodeStatusEnumToJSON = NodeStatusEnumToJSON;
