"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeHealthDTOToJSON = exports.NodeHealthDTOFromJSONTyped = exports.NodeHealthDTOFromJSON = exports.instanceOfNodeHealthDTO = void 0;
const NodeStatusEnum_1 = require("./NodeStatusEnum");
/**
 * Check if a given object implements the NodeHealthDTO interface.
 */
function instanceOfNodeHealthDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "apiNode" in value;
    isInstance = isInstance && "db" in value;
    return isInstance;
}
exports.instanceOfNodeHealthDTO = instanceOfNodeHealthDTO;
function NodeHealthDTOFromJSON(json) {
    return NodeHealthDTOFromJSONTyped(json, false);
}
exports.NodeHealthDTOFromJSON = NodeHealthDTOFromJSON;
function NodeHealthDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        apiNode: (0, NodeStatusEnum_1.NodeStatusEnumFromJSON)(json["apiNode"]),
        db: (0, NodeStatusEnum_1.NodeStatusEnumFromJSON)(json["db"]),
    };
}
exports.NodeHealthDTOFromJSONTyped = NodeHealthDTOFromJSONTyped;
function NodeHealthDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        apiNode: (0, NodeStatusEnum_1.NodeStatusEnumToJSON)(value.apiNode),
        db: (0, NodeStatusEnum_1.NodeStatusEnumToJSON)(value.db),
    };
}
exports.NodeHealthDTOToJSON = NodeHealthDTOToJSON;
