"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeIdentityEqualityStrategyToJSON = exports.NodeIdentityEqualityStrategyFromJSONTyped = exports.NodeIdentityEqualityStrategyFromJSON = exports.NodeIdentityEqualityStrategy = void 0;
/**
 * Node equality strategy. Defines if the identifier for the node must be its public key or host.
 * @export
 */
exports.NodeIdentityEqualityStrategy = {
    Host: 'host',
    PublicKey: 'public-key'
};
function NodeIdentityEqualityStrategyFromJSON(json) {
    return NodeIdentityEqualityStrategyFromJSONTyped(json, false);
}
exports.NodeIdentityEqualityStrategyFromJSON = NodeIdentityEqualityStrategyFromJSON;
function NodeIdentityEqualityStrategyFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.NodeIdentityEqualityStrategyFromJSONTyped = NodeIdentityEqualityStrategyFromJSONTyped;
function NodeIdentityEqualityStrategyToJSON(value) {
    return value;
}
exports.NodeIdentityEqualityStrategyToJSON = NodeIdentityEqualityStrategyToJSON;
