"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeHealthInfoDTOToJSON = exports.NodeHealthInfoDTOFromJSONTyped = exports.NodeHealthInfoDTOFromJSON = exports.instanceOfNodeHealthInfoDTO = void 0;
const NodeHealthDTO_1 = require("./NodeHealthDTO");
/**
 * Check if a given object implements the NodeHealthInfoDTO interface.
 */
function instanceOfNodeHealthInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    return isInstance;
}
exports.instanceOfNodeHealthInfoDTO = instanceOfNodeHealthInfoDTO;
function NodeHealthInfoDTOFromJSON(json) {
    return NodeHealthInfoDTOFromJSONTyped(json, false);
}
exports.NodeHealthInfoDTOFromJSON = NodeHealthInfoDTOFromJSON;
function NodeHealthInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'status': (0, NodeHealthDTO_1.NodeHealthDTOFromJSON)(json['status']),
    };
}
exports.NodeHealthInfoDTOFromJSONTyped = NodeHealthInfoDTOFromJSONTyped;
function NodeHealthInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'status': (0, NodeHealthDTO_1.NodeHealthDTOToJSON)(value.status),
    };
}
exports.NodeHealthInfoDTOToJSON = NodeHealthInfoDTOToJSON;
