"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PluginsPropertiesDTOToJSON = exports.PluginsPropertiesDTOFromJSONTyped = exports.PluginsPropertiesDTOFromJSON = exports.instanceOfPluginsPropertiesDTO = void 0;
const runtime_1 = require("../runtime");
const AccountKeyLinkNetworkPropertiesDTO_1 = require("./AccountKeyLinkNetworkPropertiesDTO");
const AccountRestrictionNetworkPropertiesDTO_1 = require("./AccountRestrictionNetworkPropertiesDTO");
const AggregateNetworkPropertiesDTO_1 = require("./AggregateNetworkPropertiesDTO");
const HashLockNetworkPropertiesDTO_1 = require("./HashLockNetworkPropertiesDTO");
const MetadataNetworkPropertiesDTO_1 = require("./MetadataNetworkPropertiesDTO");
const MosaicNetworkPropertiesDTO_1 = require("./MosaicNetworkPropertiesDTO");
const MosaicRestrictionNetworkPropertiesDTO_1 = require("./MosaicRestrictionNetworkPropertiesDTO");
const MultisigNetworkPropertiesDTO_1 = require("./MultisigNetworkPropertiesDTO");
const NamespaceNetworkPropertiesDTO_1 = require("./NamespaceNetworkPropertiesDTO");
const SecretLockNetworkPropertiesDTO_1 = require("./SecretLockNetworkPropertiesDTO");
const TransferNetworkPropertiesDTO_1 = require("./TransferNetworkPropertiesDTO");
/**
 * Check if a given object implements the PluginsPropertiesDTO interface.
 */
function instanceOfPluginsPropertiesDTO(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfPluginsPropertiesDTO = instanceOfPluginsPropertiesDTO;
function PluginsPropertiesDTOFromJSON(json) {
    return PluginsPropertiesDTOFromJSONTyped(json, false);
}
exports.PluginsPropertiesDTOFromJSON = PluginsPropertiesDTOFromJSON;
function PluginsPropertiesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'accountlink': !(0, runtime_1.exists)(json, 'accountlink') ? undefined : (0, AccountKeyLinkNetworkPropertiesDTO_1.AccountKeyLinkNetworkPropertiesDTOFromJSON)(json['accountlink']),
        'aggregate': !(0, runtime_1.exists)(json, 'aggregate') ? undefined : (0, AggregateNetworkPropertiesDTO_1.AggregateNetworkPropertiesDTOFromJSON)(json['aggregate']),
        'lockhash': !(0, runtime_1.exists)(json, 'lockhash') ? undefined : (0, HashLockNetworkPropertiesDTO_1.HashLockNetworkPropertiesDTOFromJSON)(json['lockhash']),
        'locksecret': !(0, runtime_1.exists)(json, 'locksecret') ? undefined : (0, SecretLockNetworkPropertiesDTO_1.SecretLockNetworkPropertiesDTOFromJSON)(json['locksecret']),
        'metadata': !(0, runtime_1.exists)(json, 'metadata') ? undefined : (0, MetadataNetworkPropertiesDTO_1.MetadataNetworkPropertiesDTOFromJSON)(json['metadata']),
        'mosaic': !(0, runtime_1.exists)(json, 'mosaic') ? undefined : (0, MosaicNetworkPropertiesDTO_1.MosaicNetworkPropertiesDTOFromJSON)(json['mosaic']),
        'multisig': !(0, runtime_1.exists)(json, 'multisig') ? undefined : (0, MultisigNetworkPropertiesDTO_1.MultisigNetworkPropertiesDTOFromJSON)(json['multisig']),
        'namespace': !(0, runtime_1.exists)(json, 'namespace') ? undefined : (0, NamespaceNetworkPropertiesDTO_1.NamespaceNetworkPropertiesDTOFromJSON)(json['namespace']),
        'restrictionaccount': !(0, runtime_1.exists)(json, 'restrictionaccount') ? undefined : (0, AccountRestrictionNetworkPropertiesDTO_1.AccountRestrictionNetworkPropertiesDTOFromJSON)(json['restrictionaccount']),
        'restrictionmosaic': !(0, runtime_1.exists)(json, 'restrictionmosaic') ? undefined : (0, MosaicRestrictionNetworkPropertiesDTO_1.MosaicRestrictionNetworkPropertiesDTOFromJSON)(json['restrictionmosaic']),
        'transfer': !(0, runtime_1.exists)(json, 'transfer') ? undefined : (0, TransferNetworkPropertiesDTO_1.TransferNetworkPropertiesDTOFromJSON)(json['transfer']),
    };
}
exports.PluginsPropertiesDTOFromJSONTyped = PluginsPropertiesDTOFromJSONTyped;
function PluginsPropertiesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'accountlink': (0, AccountKeyLinkNetworkPropertiesDTO_1.AccountKeyLinkNetworkPropertiesDTOToJSON)(value.accountlink),
        'aggregate': (0, AggregateNetworkPropertiesDTO_1.AggregateNetworkPropertiesDTOToJSON)(value.aggregate),
        'lockhash': (0, HashLockNetworkPropertiesDTO_1.HashLockNetworkPropertiesDTOToJSON)(value.lockhash),
        'locksecret': (0, SecretLockNetworkPropertiesDTO_1.SecretLockNetworkPropertiesDTOToJSON)(value.locksecret),
        'metadata': (0, MetadataNetworkPropertiesDTO_1.MetadataNetworkPropertiesDTOToJSON)(value.metadata),
        'mosaic': (0, MosaicNetworkPropertiesDTO_1.MosaicNetworkPropertiesDTOToJSON)(value.mosaic),
        'multisig': (0, MultisigNetworkPropertiesDTO_1.MultisigNetworkPropertiesDTOToJSON)(value.multisig),
        'namespace': (0, NamespaceNetworkPropertiesDTO_1.NamespaceNetworkPropertiesDTOToJSON)(value.namespace),
        'restrictionaccount': (0, AccountRestrictionNetworkPropertiesDTO_1.AccountRestrictionNetworkPropertiesDTOToJSON)(value.restrictionaccount),
        'restrictionmosaic': (0, MosaicRestrictionNetworkPropertiesDTO_1.MosaicRestrictionNetworkPropertiesDTOToJSON)(value.restrictionmosaic),
        'transfer': (0, TransferNetworkPropertiesDTO_1.TransferNetworkPropertiesDTOToJSON)(value.transfer),
    };
}
exports.PluginsPropertiesDTOToJSON = PluginsPropertiesDTOToJSON;
