"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResolutionStatementPageToJSON = exports.ResolutionStatementPageFromJSONTyped = exports.ResolutionStatementPageFromJSON = exports.instanceOfResolutionStatementPage = void 0;
const Pagination_1 = require("./Pagination");
const ResolutionStatementInfoDTO_1 = require("./ResolutionStatementInfoDTO");
/**
 * Check if a given object implements the ResolutionStatementPage interface.
 */
function instanceOfResolutionStatementPage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfResolutionStatementPage = instanceOfResolutionStatementPage;
function ResolutionStatementPageFromJSON(json) {
    return ResolutionStatementPageFromJSONTyped(json, false);
}
exports.ResolutionStatementPageFromJSON = ResolutionStatementPageFromJSON;
function ResolutionStatementPageFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'data': (json['data'].map(ResolutionStatementInfoDTO_1.ResolutionStatementInfoDTOFromJSON)),
        'pagination': (0, Pagination_1.PaginationFromJSON)(json['pagination']),
    };
}
exports.ResolutionStatementPageFromJSONTyped = ResolutionStatementPageFromJSONTyped;
function ResolutionStatementPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': (value.data.map(ResolutionStatementInfoDTO_1.ResolutionStatementInfoDTOToJSON)),
        'pagination': (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.ResolutionStatementPageToJSON = ResolutionStatementPageToJSON;
