"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResolutionStatementDTOUnresolvedToJSON = exports.ResolutionStatementDTOUnresolvedFromJSONTyped = exports.ResolutionStatementDTOUnresolvedFromJSON = exports.instanceOfResolutionStatementDTOUnresolved = void 0;
/**
 * Check if a given object implements the ResolutionStatementDTOUnresolved interface.
 */
function instanceOfResolutionStatementDTOUnresolved(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfResolutionStatementDTOUnresolved = instanceOfResolutionStatementDTOUnresolved;
function ResolutionStatementDTOUnresolvedFromJSON(json) {
    return ResolutionStatementDTOUnresolvedFromJSONTyped(json, false);
}
exports.ResolutionStatementDTOUnresolvedFromJSON = ResolutionStatementDTOUnresolvedFromJSON;
function ResolutionStatementDTOUnresolvedFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.ResolutionStatementDTOUnresolvedFromJSONTyped = ResolutionStatementDTOUnresolvedFromJSONTyped;
function ResolutionStatementDTOUnresolvedToJSON(value) {
    return value;
}
exports.ResolutionStatementDTOUnresolvedToJSON = ResolutionStatementDTOUnresolvedToJSON;
