"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecretLockInfoDTOToJSON = exports.SecretLockInfoDTOFromJSONTyped = exports.SecretLockInfoDTOFromJSON = exports.instanceOfSecretLockInfoDTO = void 0;
const SecretLockEntryDTO_1 = require("./SecretLockEntryDTO");
/**
 * Check if a given object implements the SecretLockInfoDTO interface.
 */
function instanceOfSecretLockInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "lock" in value;
    return isInstance;
}
exports.instanceOfSecretLockInfoDTO = instanceOfSecretLockInfoDTO;
function SecretLockInfoDTOFromJSON(json) {
    return SecretLockInfoDTOFromJSONTyped(json, false);
}
exports.SecretLockInfoDTOFromJSON = SecretLockInfoDTOFromJSON;
function SecretLockInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: json["id"],
        lock: (0, SecretLockEntryDTO_1.SecretLockEntryDTOFromJSON)(json["lock"]),
    };
}
exports.SecretLockInfoDTOFromJSONTyped = SecretLockInfoDTOFromJSONTyped;
function SecretLockInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        lock: (0, SecretLockEntryDTO_1.SecretLockEntryDTOToJSON)(value.lock),
    };
}
exports.SecretLockInfoDTOToJSON = SecretLockInfoDTOToJSON;
