"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecretProofTransactionBodyDTOToJSON = exports.SecretProofTransactionBodyDTOFromJSONTyped = exports.SecretProofTransactionBodyDTOFromJSON = exports.instanceOfSecretProofTransactionBodyDTO = void 0;
const LockHashAlgorithmEnum_1 = require("./LockHashAlgorithmEnum");
/**
 * Check if a given object implements the SecretProofTransactionBodyDTO interface.
 */
function instanceOfSecretProofTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "recipientAddress" in value;
    isInstance = isInstance && "secret" in value;
    isInstance = isInstance && "hashAlgorithm" in value;
    isInstance = isInstance && "proof" in value;
    return isInstance;
}
exports.instanceOfSecretProofTransactionBodyDTO = instanceOfSecretProofTransactionBodyDTO;
function SecretProofTransactionBodyDTOFromJSON(json) {
    return SecretProofTransactionBodyDTOFromJSONTyped(json, false);
}
exports.SecretProofTransactionBodyDTOFromJSON = SecretProofTransactionBodyDTOFromJSON;
function SecretProofTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        recipientAddress: json["recipientAddress"],
        secret: json["secret"],
        hashAlgorithm: (0, LockHashAlgorithmEnum_1.LockHashAlgorithmEnumFromJSON)(json["hashAlgorithm"]),
        proof: json["proof"],
    };
}
exports.SecretProofTransactionBodyDTOFromJSONTyped = SecretProofTransactionBodyDTOFromJSONTyped;
function SecretProofTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        recipientAddress: value.recipientAddress,
        secret: value.secret,
        hashAlgorithm: (0, LockHashAlgorithmEnum_1.LockHashAlgorithmEnumToJSON)(value.hashAlgorithm),
        proof: value.proof,
    };
}
exports.SecretProofTransactionBodyDTOToJSON = SecretProofTransactionBodyDTOToJSON;
