"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerDTOToJSON = exports.ServerDTOFromJSONTyped = exports.ServerDTOFromJSON = exports.instanceOfServerDTO = void 0;
const DeploymentDTO_1 = require("./DeploymentDTO");
/**
 * Check if a given object implements the ServerDTO interface.
 */
function instanceOfServerDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "restVersion" in value;
    isInstance = isInstance && "sdkVersion" in value;
    isInstance = isInstance && "deployment" in value;
    return isInstance;
}
exports.instanceOfServerDTO = instanceOfServerDTO;
function ServerDTOFromJSON(json) {
    return ServerDTOFromJSONTyped(json, false);
}
exports.ServerDTOFromJSON = ServerDTOFromJSON;
function ServerDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'restVersion': json['restVersion'],
        'sdkVersion': json['sdkVersion'],
        'deployment': (0, DeploymentDTO_1.DeploymentDTOFromJSON)(json['deployment']),
    };
}
exports.ServerDTOFromJSONTyped = ServerDTOFromJSONTyped;
function ServerDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'restVersion': value.restVersion,
        'sdkVersion': value.sdkVersion,
        'deployment': (0, DeploymentDTO_1.DeploymentDTOToJSON)(value.deployment),
    };
}
exports.ServerDTOToJSON = ServerDTOToJSON;
