"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SourceDTOToJSON = exports.SourceDTOFromJSONTyped = exports.SourceDTOFromJSON = exports.instanceOfSourceDTO = void 0;
/**
 * Check if a given object implements the SourceDTO interface.
 */
function instanceOfSourceDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "primaryId" in value;
    isInstance = isInstance && "secondaryId" in value;
    return isInstance;
}
exports.instanceOfSourceDTO = instanceOfSourceDTO;
function SourceDTOFromJSON(json) {
    return SourceDTOFromJSONTyped(json, false);
}
exports.SourceDTOFromJSON = SourceDTOFromJSON;
function SourceDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        primaryId: json["primaryId"],
        secondaryId: json["secondaryId"],
    };
}
exports.SourceDTOFromJSONTyped = SourceDTOFromJSONTyped;
function SourceDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        primaryId: value.primaryId,
        secondaryId: value.secondaryId,
    };
}
exports.SourceDTOToJSON = SourceDTOToJSON;
