"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StageEnumToJSON = exports.StageEnumFromJSONTyped = exports.StageEnumFromJSON = exports.StageEnum = void 0;
/**
 * Type of stage:
 * * 0 - Prevote.
 * * 1 - Precommit.
 * * 2 - Count.
 * @export
 */
exports.StageEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
};
function StageEnumFromJSON(json) {
    return StageEnumFromJSONTyped(json, false);
}
exports.StageEnumFromJSON = StageEnumFromJSON;
function StageEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.StageEnumFromJSONTyped = StageEnumFromJSONTyped;
function StageEnumToJSON(value) {
    return value;
}
exports.StageEnumToJSON = StageEnumToJSON;
