"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferNetworkPropertiesDTOToJSON = exports.TransferNetworkPropertiesDTOFromJSONTyped = exports.TransferNetworkPropertiesDTOFromJSON = exports.instanceOfTransferNetworkPropertiesDTO = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the TransferNetworkPropertiesDTO interface.
 */
function instanceOfTransferNetworkPropertiesDTO(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfTransferNetworkPropertiesDTO = instanceOfTransferNetworkPropertiesDTO;
function TransferNetworkPropertiesDTOFromJSON(json) {
    return TransferNetworkPropertiesDTOFromJSONTyped(json, false);
}
exports.TransferNetworkPropertiesDTOFromJSON = TransferNetworkPropertiesDTOFromJSON;
function TransferNetworkPropertiesDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        maxMessageSize: !(0, runtime_1.exists)(json, "maxMessageSize")
            ? undefined
            : json["maxMessageSize"],
    };
}
exports.TransferNetworkPropertiesDTOFromJSONTyped = TransferNetworkPropertiesDTOFromJSONTyped;
function TransferNetworkPropertiesDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        maxMessageSize: value.maxMessageSize,
    };
}
exports.TransferNetworkPropertiesDTOToJSON = TransferNetworkPropertiesDTOToJSON;
