"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionGroupEnumToJSON = exports.TransactionGroupEnumFromJSONTyped = exports.TransactionGroupEnumFromJSON = exports.TransactionGroupEnum = void 0;
/**
 * A transaction could be classified in the following groups:
 * * Unconfirmed: The transaction reached the P2P network. At this point, it is not guaranteed that the transaction will be included in a block.
 * * Confirmed: The transaction is included in a block.
 * * Partial: The transaction requires to be cosigned by other transaction participants in order to be included in a block.
 * * Failed: The transaction did not pass the network validation, and it was rejected.
 * @export
 */
exports.TransactionGroupEnum = {
    Unconfirmed: 'unconfirmed',
    Confirmed: 'confirmed',
    Failed: 'failed',
    Partial: 'partial'
};
function TransactionGroupEnumFromJSON(json) {
    return TransactionGroupEnumFromJSONTyped(json, false);
}
exports.TransactionGroupEnumFromJSON = TransactionGroupEnumFromJSON;
function TransactionGroupEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.TransactionGroupEnumFromJSONTyped = TransactionGroupEnumFromJSONTyped;
function TransactionGroupEnumToJSON(value) {
    return value;
}
exports.TransactionGroupEnumToJSON = TransactionGroupEnumToJSON;
