"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionPageToJSON = exports.TransactionPageFromJSONTyped = exports.TransactionPageFromJSON = exports.instanceOfTransactionPage = void 0;
const Pagination_1 = require("./Pagination");
const TransactionInfoDTO_1 = require("./TransactionInfoDTO");
/**
 * Check if a given object implements the TransactionPage interface.
 */
function instanceOfTransactionPage(value) {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;
    return isInstance;
}
exports.instanceOfTransactionPage = instanceOfTransactionPage;
function TransactionPageFromJSON(json) {
    return TransactionPageFromJSONTyped(json, false);
}
exports.TransactionPageFromJSON = TransactionPageFromJSON;
function TransactionPageFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        data: json["data"].map(TransactionInfoDTO_1.TransactionInfoDTOFromJSON),
        pagination: (0, Pagination_1.PaginationFromJSON)(json["pagination"]),
    };
}
exports.TransactionPageFromJSONTyped = TransactionPageFromJSONTyped;
function TransactionPageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        data: value.data.map(TransactionInfoDTO_1.TransactionInfoDTOToJSON),
        pagination: (0, Pagination_1.PaginationToJSON)(value.pagination),
    };
}
exports.TransactionPageToJSON = TransactionPageToJSON;
