"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionStatementDTOToJSON = exports.TransactionStatementDTOFromJSONTyped = exports.TransactionStatementDTOFromJSON = exports.instanceOfTransactionStatementDTO = void 0;
const SourceDTO_1 = require("./SourceDTO");
const TransactionStatementDTOReceiptsInner_1 = require("./TransactionStatementDTOReceiptsInner");
/**
 * Check if a given object implements the TransactionStatementDTO interface.
 */
function instanceOfTransactionStatementDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "receipts" in value;
    return isInstance;
}
exports.instanceOfTransactionStatementDTO = instanceOfTransactionStatementDTO;
function TransactionStatementDTOFromJSON(json) {
    return TransactionStatementDTOFromJSONTyped(json, false);
}
exports.TransactionStatementDTOFromJSON = TransactionStatementDTOFromJSON;
function TransactionStatementDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'height': json['height'],
        'source': (0, SourceDTO_1.SourceDTOFromJSON)(json['source']),
        'receipts': (json['receipts'].map(TransactionStatementDTOReceiptsInner_1.TransactionStatementDTOReceiptsInnerFromJSON)),
    };
}
exports.TransactionStatementDTOFromJSONTyped = TransactionStatementDTOFromJSONTyped;
function TransactionStatementDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'height': value.height,
        'source': (0, SourceDTO_1.SourceDTOToJSON)(value.source),
        'receipts': (value.receipts.map(TransactionStatementDTOReceiptsInner_1.TransactionStatementDTOReceiptsInnerToJSON)),
    };
}
exports.TransactionStatementDTOToJSON = TransactionStatementDTOToJSON;
