"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionInfoDTOToJSON = exports.TransactionInfoDTOFromJSONTyped = exports.TransactionInfoDTOFromJSON = exports.instanceOfTransactionInfoDTO = void 0;
const TransactionInfoDTOMeta_1 = require("./TransactionInfoDTOMeta");
const TransactionInfoDTOTransaction_1 = require("./TransactionInfoDTOTransaction");
/**
 * Check if a given object implements the TransactionInfoDTO interface.
 */
function instanceOfTransactionInfoDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "transaction" in value;
    return isInstance;
}
exports.instanceOfTransactionInfoDTO = instanceOfTransactionInfoDTO;
function TransactionInfoDTOFromJSON(json) {
    return TransactionInfoDTOFromJSONTyped(json, false);
}
exports.TransactionInfoDTOFromJSON = TransactionInfoDTOFromJSON;
function TransactionInfoDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'meta': (0, TransactionInfoDTOMeta_1.TransactionInfoDTOMetaFromJSON)(json['meta']),
        'transaction': (0, TransactionInfoDTOTransaction_1.TransactionInfoDTOTransactionFromJSON)(json['transaction']),
    };
}
exports.TransactionInfoDTOFromJSONTyped = TransactionInfoDTOFromJSONTyped;
function TransactionInfoDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'meta': (0, TransactionInfoDTOMeta_1.TransactionInfoDTOMetaToJSON)(value.meta),
        'transaction': (0, TransactionInfoDTOTransaction_1.TransactionInfoDTOTransactionToJSON)(value.transaction),
    };
}
exports.TransactionInfoDTOToJSON = TransactionInfoDTOToJSON;
