"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferTransactionBodyDTOToJSON = exports.TransferTransactionBodyDTOFromJSONTyped = exports.TransferTransactionBodyDTOFromJSON = exports.instanceOfTransferTransactionBodyDTO = void 0;
const runtime_1 = require("../runtime");
const UnresolvedMosaic_1 = require("./UnresolvedMosaic");
/**
 * Check if a given object implements the TransferTransactionBodyDTO interface.
 */
function instanceOfTransferTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "recipientAddress" in value;
    isInstance = isInstance && "mosaics" in value;
    return isInstance;
}
exports.instanceOfTransferTransactionBodyDTO = instanceOfTransferTransactionBodyDTO;
function TransferTransactionBodyDTOFromJSON(json) {
    return TransferTransactionBodyDTOFromJSONTyped(json, false);
}
exports.TransferTransactionBodyDTOFromJSON = TransferTransactionBodyDTOFromJSON;
function TransferTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        recipientAddress: json["recipientAddress"],
        mosaics: json["mosaics"].map(UnresolvedMosaic_1.UnresolvedMosaicFromJSON),
        message: !(0, runtime_1.exists)(json, "message") ? undefined : json["message"],
    };
}
exports.TransferTransactionBodyDTOFromJSONTyped = TransferTransactionBodyDTOFromJSONTyped;
function TransferTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        recipientAddress: value.recipientAddress,
        mosaics: value.mosaics.map(UnresolvedMosaic_1.UnresolvedMosaicToJSON),
        message: value.message,
    };
}
exports.TransferTransactionBodyDTOToJSON = TransferTransactionBodyDTOToJSON;
