"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VotingKeyLinkTransactionBodyDTOToJSON = exports.VotingKeyLinkTransactionBodyDTOFromJSONTyped = exports.VotingKeyLinkTransactionBodyDTOFromJSON = exports.instanceOfVotingKeyLinkTransactionBodyDTO = void 0;
const LinkActionEnum_1 = require("./LinkActionEnum");
/**
 * Check if a given object implements the VotingKeyLinkTransactionBodyDTO interface.
 */
function instanceOfVotingKeyLinkTransactionBodyDTO(value) {
    let isInstance = true;
    isInstance = isInstance && "linkedPublicKey" in value;
    isInstance = isInstance && "startEpoch" in value;
    isInstance = isInstance && "endEpoch" in value;
    isInstance = isInstance && "linkAction" in value;
    return isInstance;
}
exports.instanceOfVotingKeyLinkTransactionBodyDTO = instanceOfVotingKeyLinkTransactionBodyDTO;
function VotingKeyLinkTransactionBodyDTOFromJSON(json) {
    return VotingKeyLinkTransactionBodyDTOFromJSONTyped(json, false);
}
exports.VotingKeyLinkTransactionBodyDTOFromJSON = VotingKeyLinkTransactionBodyDTOFromJSON;
function VotingKeyLinkTransactionBodyDTOFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'linkedPublicKey': json['linkedPublicKey'],
        'startEpoch': json['startEpoch'],
        'endEpoch': json['endEpoch'],
        'linkAction': (0, LinkActionEnum_1.LinkActionEnumFromJSON)(json['linkAction']),
    };
}
exports.VotingKeyLinkTransactionBodyDTOFromJSONTyped = VotingKeyLinkTransactionBodyDTOFromJSONTyped;
function VotingKeyLinkTransactionBodyDTOToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'linkedPublicKey': value.linkedPublicKey,
        'startEpoch': value.startEpoch,
        'endEpoch': value.endEpoch,
        'linkAction': (0, LinkActionEnum_1.LinkActionEnumToJSON)(value.linkAction),
    };
}
exports.VotingKeyLinkTransactionBodyDTOToJSON = VotingKeyLinkTransactionBodyDTOToJSON;
